### ISSUE TITLE
Apparently no group ('g') support

### ISSUE THREAD

**Issue by ismaelharunid** [pywavefront/PyWavefront#112]
The 'g' lines (groups) are not supported.

**Comment by einarf** [comment]
This is correct. Groups are not supported. Please elaborate what this issue is about.

**Comment by ismaelharunid** [comment]
Just confirming.  But can you tel me was it just a low priority, oversight or not to be implemented?  If not to be implemented, do you think it's not needed?  If I added this would it be of value?
Oh and I sorry, I'm not sure if you got a notice but I tried to commit my branch onto yours bu accident.  Obviously it didn't take, but my apologizes anyway.

**Comment by einarf** [comment]
Not supporting grouping should not stop you from loading an obj file. It just means the the vertex data will not be grouped the way you want it. The main reason this libraray doesn't support groups is because it groups vertex by materials to make the objects fast to render. A 2.x version of pywavefront would be needed to actually add support for this.
