### ISSUE TITLE
Cache option not working?

### ISSUE THREAD

**Issue by Cocco17** [pywavefront/PyWavefront#139]
I am trying to speed up my application by using the cache option, if the application has previously already read the 3D-Object file. However, when setting the cache option to True, the created pywavefront object has no vertices at all. Without the cache option, the creation works fine - anybody here who has experienced the same problem?

**Comment by einarf** [comment]
The cache doesn't resolve the vertex data into python objects by default  because that would be extremely slow.

You can make your own loader like this:
https://github.com/moderngl/moderngl-window/blob/268c8d886e99e9aae05ea3bb5941994dc2a99569/moderngl_window/loaders/scene/wavefront.py#L52-L68

The function gets a file descripter and a data length for the vertices and you can do whatever you want with them. I just load it directly into a OpenGL buffer ready for rendering.

If we restored the original python data structures by default it would pretty much be unusable for very large files.

**Comment by Cocco17** [comment]
I used another workaround by simply storing the gl.MeshData in a pickle file - anyways, thanks a lot for the quick response!

**Comment by einarf** [comment]
> I used another workaround by simply storing the gl.MeshData in a pickle file - anyways, thanks a lot for the quick response!

Also works, Not as fast, but probably fast enough. It can be a problem with very large objects. I've cut load times from 3 minutes to seconds with the binary fomat.
